config/routes.rb
Rails.application.routes.draw do
  #namespace :admin do
    #get 'orders/show'
  #end
  #namespace :admin do
    #get 'customers/index'
    #get 'customers/show'
    #get 'customers/edit'
  #end
  #namespace :admin do
    #get 'genres/index'
    #get 'genres/edit'
  #end
  #namespace :admin do
    #get 'items/new'
    #get 'items/index'
    #get 'items/show'
    #get 'items/edit'
  #end
  #namespace :admin do
    #get 'homes/top'
  #end
  #namespace :public do
    #get 'addresses/index'
    #get 'addresses/edit'
  #end
  #namespace :public do
   # get 'orders/new'
    #get 'orders/index'
    #get 'orders/show'
    #get 'orders/confirm'
  #end
  #namespace :public do
    #get 'cart_items/index'
  #end
  #namespace :public do
    #get 'items/index'
    #get 'items/show'
  #end
  #namespace :public do
    #get 'customers/show'
    #get 'customers/edit'
    #get 'customers/unsubscribe'
  #end
  #namespace :public do
    #get 'homes/top'
    #get 'homes/about'
 # end
# 顧客用URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # 会員用
    root to: 'public/homes#top'
    get '/about' => 'public/homes#about', as: 'about'

    get '/customers/my_page' => 'public/customers#show', as: 'my_page'
    get '/customers/information/edit' => 'public/customers#edit', as: 'edit_customer'
    patch '/customers/information' => 'public/customers#update', as: 'customer'
    get '/customers/unsubscribe' => 'public/customers#unsubscribe', as: 'unsubscribe'
    patch '/customers/withdraw' => 'public/customers#withdraw', as: 'withdraw'

    delete '/cart_items/destroy_all' => 'public/cart_items#destroy_all', as: 'destroy_all'

    post '/orders/confirm' => 'public/orders#confirm', as: 'confirm'
    get '/orders/thanks' => 'public/orders#thanks', as: 'thanks'
    get '/search' => 'public/items#search', as: 'search'

    scope module: :public do
      resources :items, only: [:index, :show]
      resources :cart_items, only: [:index, :update, :destroy, :create]
      resources :orders, only: [:new, :create, :index, :show]
      resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    end

  # 管理者用
  namespace :admin do
    root to: 'homes#top'
    get 'customer_orders' => 'homes#customer_orders', as: 'customer_orders'

    resources :items, only: [:index, :new, :create, :show, :edit, :update]

    resources :genres, only: [:index, :create, :edit, :update]

    resources :customers, except: [:new, :create, :destroy]

    resources :orders, only: [:show, :update]

    patch '/admin/order_details/:id' => 'order_details#update', as: 'order_detail'
  end
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre


  has_one_attached :image

  validates :name, presence: true

  validates :image, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :is_active, inclusion: { in: [true,false] }

  TAX_RATE = 1.1

# 税込価格の表記
  def add_tax_price
    (self.price * TAX_RATE).floor
  end
# 商品画像の記述

  #def get_image(width, height)
    #image.variant(resize: "#{width}x#{height}!").processed
  #end


  def get_image(width, height)
    image.variant(resize: "#{width}x#{height}!").processed
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
  @item = Item.new
  end

  def create
  @item = Item.new(item_params)
   if @item.save
   redirect_to admin_item_path(@item), notice: "You have created item successfully."
   else
  flash.now[:notice] = "create item error"
   render :new
   end
  end

  def index
  @items = Item.page(params[:page]).per(10)
  end

  def show
  @item = Item.find(params[:id])
  end

  def edit
  @item = Item.find(params[:id])
  end
  
  def update
  @item = Item.find(params[:id])
  if@item.update(item_params)
  redirect_to admin_item_path(@item), notice: "You have updated item successfully."
  else
  flash.now[:notice] = "update item error"
  render :edit
  end
  end
    private
  # ストロングパラメータ
  def item_params
  params.require(:item).permit(:name, :introduction, :genre_id, :price, :is_active, :image)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 px-sm-0 offset-sm-1">
    <h5>
      <span class=" p-2" style="background-color: #eee;">商品編集</span>
    </h5>
    </div>
  </div>
    <div class="row col-md-auto">
    <div class="col-sm-12 px-sm-0 mb-5">
 <%= form_with model: @item, url: admin_item_path, local: true do |f| %>
  <table class="table table-borderless col-8">
   <tr>
    <div class="form-group">
          <th><%= f.label :商品画像 %></th>
          <td><%= f.file_field :image, placeholder: "商品画像", accept: "image/*" %>  </td>
        </div>
      </tr>
      <tr>
        <div class="form-group">
          <th><%= f.label :商品名 %></th>
          <td><%= f.text_field :name, placeholder:"商品名" %></td>
        </div>
      </tr>
      <tr>
        <div class="form-group">
          <th><%= f.label :商品説明 %></th>
          <td><%= f.text_area :introduction, size: "50x5", placeholder:"ここに説明文を記述します" %></td>
        </div>
      </tr>
      <tr>
        <div class="form-group">
          <th><%= f.label :ジャンル %></th>
          <td><%= f.collection_select :genre_id, Genre.all, :id, :name, :prompt => "--選択してください--" %></td>
        </div>
      </tr>
      <tr>
        <div class="form-group">
          <th><%= f.label :税抜価格 %></th>
          <td><%= f.text_field :price, placeholder:"1000" %>円</td>
        </div>
      </tr>
      <tr>
        <div class="form-group">
          <th><%= f.label :販売ステータス %></th>
          <td><%= f.radio_button :is_active, true, checked: true %>
          <%= f.label :is_active, "販売中" %>
          <%= f.radio_button :is_active, false %>
          <%= f.label :is_active, "販売中止" %></td>
        </div>
      </tr>
      <tr>
        <div class="form-action">
          <td><%= f.submit "変更を保存", class:"btn btn-success" %></td>
        </div>
      </tr>
      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 px-sm-0 offset-sm-1">
    <h4>
      <span class=" mb-2" style="background-color: #eee;">商品一覧</span>
    </h4>
     </div>
    <div class="col-sm-1 px-sm-0 text-right mb-2">
      <%= link_to new_admin_item_path, class:"text-secondary" do %>
        <h1><i class="fa-solid fa-circle-plus"></i></h1>
      <% end %>
    </div>

  <div class="col-sm-10 px-sm-0 mx-auto mt-3 ">
  <table class="table table-borderless">
    <thead>
     <tr class="table-secondary">
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
      </tr>
      </thead>
<% @items.each do |item| %>
    <tbody>
     <tr>
      <td><%= item.id %></td>
       <td><%= link_to admin_item_path(item.id) do %>
        <u><%= item.name %></u>
         </td>
          <% end %>
      <td>¥<%= item.price.to_s(:delimited) %></td>
      <td><%= item.genre.name %></td>
      <td><% if item.is_active == true %>
       <p class="text-success font-weight-bold">販売中</p>
        <% else %>
       <p class="text-secondary font-weight-bold">販売停止中</p>
        <% end %>
       </td>
      </tr>
    </tbody>
    <% end %>
   </table>
      <%= paginate @items %>
  </div>
 </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 px-sm-0 offset-sm-1">
    <h5>
      <span class=" p-2" style="background-color: #eee;">商品新規登録</span>
    </h5>
    </div>
  </div>
    <div class="row col-md-auto">
    <div class="col-sm-12 px-sm-0 mb-5">
 <%= form_with model: @item, url:"/admin/items" do |f| %>
  <table class="table table-borderless col-8">

   <tr>
    <div class="form-group">
    <th><%= f.label :商品画像 %></th>
     <th><%= f.file_field :image, accept: "image/*" %></th>
      </div>
   </tr>

   <tr><th>商品名</th>
 　 <td><%= f.text_field :name, placeholder:"商品名" %></td>
　 </tr>

   <tr><th>本文</th>
    <td><%= f.text_area :introduction, size: "50x5", placeholder:"ここに説明文を記述します" %></td>
　 </tr>

　 <tr>
   <div class="form-group">
    <th><%= f.label :ジャンル %></th>
     <td><%= f.collection_select :genre_id, Genre.all, :id, :name, :prompt => "--選択してください--" %></td>
     </div>
   </tr>

   <tr><th>税抜価格</th>
    <td><%= f.text_field :price, placeholder:"1000" %>円</td>

　  <tr><th>販売ステータス</th>
　   <td><%= f.radio_button :is_active, true, checked: true %>
     <%= f.label :is_active, "販売中" %>
     <%= f.radio_button :is_active, false %>
     <%= f.label :is_active, "販売停止中" %></td></th></tr>

  <tr><th><%= f.submit "新規登録", class:"btn btn-success" %></td></th></tr>
       </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class='container my-5'>

  <div class='row mb-5 d-flex'>
    <h4>
      <span class=" p-2" style="background-color: #eee;">商品詳細</span>
    </h4>
        <div class=" col-sx-12 col-lg-4 mt-3 ">
      <div class="text-center ">
 <%= image_tag @item.get_image(300,200) %>
      </div>
    </div>
    <div class="col-sx-12 col-md-12 col-lg-5 mt-6 ">
    <table class="table table-borderless">

      <tr><th>商品名</th>
      <td><p><%= @item.name %></p></td>
      </tr>
      <tr><th>商品説明</th></th>
      <td><p><%= simple_format(@item.introduction)%></p></td>
      </tr>
      <tr><th>ジャンル</th></th>
      <td><%= @item.genre.name %></td>
      <tr><th>税込価格<br>(税抜価格)</th></th>
      <td><h5> <%=@item.add_tax_price.to_s(:delimited) %> (<%= @item.price.to_s(:delimited) %>)円</h5></td>
      <tr><th>販売ステータス</th></th>
      <td><%  if @item.is_active == true %>
        <p class="text-success">販売中</p>
      <% else %>
        <p class="text-secondary">販売停止中です</p></td>
      <% end %>
        <tr><td><%= link_to "編集する", edit_admin_item_path, class:"btn btn-success" %></td></tr>
      </table>
       </div>
    </div>
   </div>