config/routes.rb
Rails.application.routes.draw do
  #namespace :admin do
    #get 'orders/show'
  #end
  #namespace :admin do
    #get 'customers/index'
    #get 'customers/show'
    #get 'customers/edit'
  #end
  #namespace :admin do
    #get 'genres/index'
    #get 'genres/edit'
  #end
  #namespace :admin do
    #get 'items/new'
    #get 'items/index'
    #get 'items/show'
    #get 'items/edit'
  #end
  #namespace :admin do
    #get 'homes/top'
  #end
  #namespace :public do
    #get 'addresses/index'
    #get 'addresses/edit'
  #end
  #namespace :public do
   # get 'orders/new'
    #get 'orders/index'
    #get 'orders/show'
    #get 'orders/confirm'
  #end
  #namespace :public do
    #get 'cart_items/index'
  #end
  #namespace :public do
    #get 'items/index'
    #get 'items/show'
  #end
  #namespace :public do
    #get 'customers/show'
    #get 'customers/edit'
    #get 'customers/unsubscribe'
  #end
  #namespace :public do
    #get 'homes/top'
    #get 'homes/about'
 # end
# 顧客用URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # 会員用
    root to: 'public/homes#top'
    get '/about' => 'public/homes#about', as: 'about'

    get '/customers/my_page' => 'public/customers#show', as: 'my_page'
    get '/customers/information/edit' => 'public/customers#edit', as: 'edit_customer'
    patch '/customers/information' => 'public/customers#update', as: 'customer'
    get '/customers/unsubscribe' => 'public/customers#unsubscribe', as: 'unsubscribe'
    patch '/customers/withdraw' => 'public/customers#withdraw', as: 'withdraw'

    delete '/cart_items/destroy_all' => 'public/cart_items#destroy_all', as: 'destroy_all'

    post '/orders/confirm' => 'public/orders#confirm', as: 'confirm'
    get '/orders/thanks' => 'public/orders#thanks', as: 'thanks'
    get '/search' => 'public/items#search', as: 'search'

    scope module: :public do
      resources :items, only: [:index, :show]
      resources :cart_items, only: [:index, :update, :destroy, :create]
      resources :orders, only: [:new, :create, :index, :show]
      resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    end

  # 管理者用
  namespace :admin do
    root to: 'homes#top'
    get 'customer_orders' => 'homes#customer_orders', as: 'customer_orders'

    resources :items, only: [:index, :new, :create, :show, :edit, :update]

    resources :genres, only: [:index, :create, :edit, :update]

    resources :customers, except: [:new, :create, :destroy]

    resources :orders, only: [:show, :update]

    patch '/admin/order_details/:id' => 'order_details#update', as: 'order_detail'
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  validates :email, uniqueness: true
  
  def full_name
    last_name + '' + first_name
  end

  def full_name_kana
    last_name_kana + '' + first_name_kana
  end
#is_active == falseを入れるとログイン前に戻される⇒falseにするとログインに戻されるので
#trueでバリテーションがかからない状態になる
  def active_for_authentication?
    super && (is_active == true)
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update]

  def index
    @customers = Customer.all
  end

  def show
  end

  def edit
  end

  def update
    customer = Customer.find(params[:id])
    if customer.update!(customer_params)
      redirect_to admin_customer_path(customer)
    else
      render :edit
    end
  end

  private

  def set_customer
    @customer = Customer.find(params[:id])
  end

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :address, :email, :postal_code, :telephone_number, :is_active )
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class ="row">
    <h5 class="my-5">
      <span class ="p-2" style="background-color: #eee;">
        <%= @customer.full_name %>さんの会員情報編集
      </span>
    </h5>
  </div>
  <div class="row">
    <div class="col">
      <%= form_with model: [:admin, @customer] do |f| %>
      <table class="table table-borderless">
        <tr>
          <td>会員ID</td>
          <td><%= @customer.id %></td>
        </tr>

        <tr>
          <td>氏名</td>
          <td><%= f.text_field :last_name %>　<%= f.text_field :first_name %></td>
        </tr>

        <tr>
          <td>フリガナ</td>
          <td><%= f.text_field :last_name_kana %>　<%= f.text_field :first_name_kana %></td>
        </tr>

        <tr>
          <td>郵便番号</td>
          <td><%= f.text_field :postal_code %></td>
          <td></td>
        </tr>

        <tr>
          <td>住所</td>
          <td><%= f.text_field :address %></td>
          <td></td>
        </tr>

        <tr>
          <td>電話番号</td>
          <td><%= f.text_field :telephone_number %></td>
          <td></td>
        </tr>

        <tr>
          <td>メールアドレス</td>
          <td><%= f.text_field :email %></td>
          <td></td>
        </tr>

        <tr>
          <td>会員ステータス</td>
          <td >
            <%= f.radio_button :is_active, :true %>
            <%= f.label :is_active, "有効" %>

            <%= f.radio_button :is_active, :false %>
            <%= f.label :is_active, "退会" %>
          </td>
        </tr>

        <tr>
          <td></td>
          <td><%= f.submit "変更を保存", class:"btn btn-success" %></td>
        </tr>
      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class ="container">
  <div class ="row">
    <h5 class="my-5">
      <span class ="p-2" style="background-color: #eee;">
        会員一覧
      </span>
    </h5>
  </div>
  <div class ="row">
    <div class = "col">
      <table class ="table">
        <thead>
          <tr class ="p-2" style="background-color: #eee;">
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.id %></td>
              <td>
                <%= link_to customer.full_name, admin_customer_path(customer) %>
              </td>
              <td><%= customer.email %></td>
              <% if customer.is_active %>
                <td class = "text-success">有効</td>
              <% else %>
                <td class = "text-secondary">退会</td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row-8">
    <div class="col">
      <h5 class="my-5">
        <span class ="p-2" style="background-color: #eee;">
          <%= @customer.full_name %>さんの会員詳細
        </span>
      </h5>
      <div class="d-flex align-items-center">
        <table class="table table-borderless">
          <tr>
            <th>会員ID</td>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <th>氏名</td>
            <td><%= @customer.last_name %>　<%= @customer.first_name %></td>
          </tr>

          <tr>
            <th>フリガナ</th>
            <td><%= @customer.last_name_kana %>　<%= @customer.first_name_kana %></td>
          </tr>

          <tr>
            <th>郵便番号</th>
            <td><%= @customer.postal_code %></td>
          </tr>

          <tr>
            <th>住所</th>
            <td><%= @customer.address %></td>
          </tr>

          <tr>
            <th>電話番号</th>
            <td><%= @customer.telephone_number %></td>
          </tr>

          <tr>
            <th>メールアドレス</th>
            <td><%= @customer.email %></td>
          </tr>

          <tr>
            <th>会員ステータス</th>
            <td class ="text-left">
              <% if @customer.is_active %>
                <span class = "text-success">有効</span>
              <% else %>
                <span class = "text-secondary">退会</span>
              <% end %>
            </th>
          </tr>

          <tr>
            <td></td>
            <td>
              <%= link_to "編集する", edit_admin_customer_path, class:"btn btn-success" %>
            </td>
            <td>
              <%= link_to "注文履歴一覧を見る", admin_root_path, class:"btn btn-primary" %>
            </td>
          </tr>

        </table>
      </div>
    </div>
  </div>
</div>