config/routes.rb
Rails.application.routes.draw do
  #namespace :admin do
    #get 'orders/show'
  #end
  #namespace :admin do
    #get 'customers/index'
    #get 'customers/show'
    #get 'customers/edit'
  #end
  #namespace :admin do
    #get 'genres/index'
    #get 'genres/edit'
  #end
  #namespace :admin do
    #get 'items/new'
    #get 'items/index'
    #get 'items/show'
    #get 'items/edit'
  #end
  #namespace :admin do
    #get 'homes/top'
  #end
  #namespace :public do
    #get 'addresses/index'
    #get 'addresses/edit'
  #end
  #namespace :public do
   # get 'orders/new'
    #get 'orders/index'
    #get 'orders/show'
    #get 'orders/confirm'
  #end
  #namespace :public do
    #get 'cart_items/index'
  #end
  #namespace :public do
    #get 'items/index'
    #get 'items/show'
  #end
  #namespace :public do
    #get 'customers/show'
    #get 'customers/edit'
    #get 'customers/unsubscribe'
  #end
  #namespace :public do
    #get 'homes/top'
    #get 'homes/about'
 # end
# 顧客用URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # 会員用
    root to: 'public/homes#top'
    get '/about' => 'public/homes#about', as: 'about'

    get '/customers/my_page' => 'public/customers#show', as: 'my_page'
    get '/customers/information/edit' => 'public/customers#edit', as: 'edit_customer'
    patch '/customers/information' => 'public/customers#update', as: 'customer'
    get '/customers/unsubscribe' => 'public/customers#unsubscribe', as: 'unsubscribe'
    patch '/customers/withdraw' => 'public/customers#withdraw', as: 'withdraw'

    delete '/cart_items/destroy_all' => 'public/cart_items#destroy_all', as: 'destroy_all'

    post '/orders/confirm' => 'public/orders#confirm', as: 'confirm'
    get '/orders/thanks' => 'public/orders#thanks', as: 'thanks'
    get '/search' => 'public/items#search', as: 'search'

    scope module: :public do
      resources :items, only: [:index, :show]
      resources :cart_items, only: [:index, :update, :destroy, :create]
      resources :orders, only: [:new, :create, :index, :show]
      resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    end

  # 管理者用
  namespace :admin do
    root to: 'homes#top'
    get 'customer_orders' => 'homes#customer_orders', as: 'customer_orders'

    resources :items, only: [:index, :new, :create, :show, :edit, :update]

    resources :genres, only: [:index, :create, :edit, :update]

    resources :customers, except: [:new, :create, :destroy]

    resources :orders, only: [:show, :update]

    patch '/admin/order_details/:id' => 'order_details#update', as: 'order_detail'
  end
end

app/views/layouts/_footer.html.erb
<footer class="py-4" style="background-color: #FFB3CB; color: #fff;">
  <div class="container text-center">
    <p class="mb-0">Copyright © 2024 Lyckatill</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg bg-body-tertiary" style="background-color: #FFB3CB;">
    <div class="container-fluid">
      <nav class="navbar bg-body-tertiary">
        <div class="container">
          <a class="navbar-brand" href="/">
            <%= link_to root_path do %>
            <%= image_tag "logo.png", size: '200x80' %>
            <% end %>
          </a>
        </div>
      </nav>
      
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <div class="d-flex flex-column w-100">
            <ul class="navbar-nav ml-auto">
            
            <!-- カスタマーがログインしている時 -->
            <% if customer_signed_in? %>
            <li class="nav-item">
            ようこそ、<%= current_customer.last_name + current_customer.first_name %>さん！
            </li>
            <li class="nav-item"><%= link_to "マイページ", my_page_path, class: "btn btn-outline-warning text-dark" %></li>
            <li class="nav-item"><%= link_to "商品一覧", items_path, class: "btn btn-outline-warning text-dark" %></li>
            <li class="nav-item"><%= link_to "カート", cart_items_path, class: "btn btn-outline-warning text-dark" %></li>
            <li class="nav-item"><%= link_to "About", about_path, class: "btn btn-outline-warning text-dark" %></li>
            <li class="nav-item"><%= link_to "ログアウト", destroy_customer_session_path, class: "btn btn-outline-warning text-dark", method: :delete %></li>
            
            <!-- 管理者がログインしている時 -->
            <% elsif admin_signed_in? %>
            <li class="nav-item"><%= link_to "商品一覧", admin_items_path, class: "btn btn-outline-warning text-dark" %></li>
            <li class="nav-item"><%= link_to "会員一覧", admin_customers_path, class: "btn btn-outline-warning text-dark" %></li>
            <li class="nav-item"><%= link_to "注文履歴一覧", admin_root_path, class: "btn btn-outline-warning text-dark" %></li>
            <li class="nav-item"><%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-outline-warning text-dark" %></li>
            <li class="nav-item"><%= link_to "About", about_path, class: "btn btn-outline-warning text-dark" %></li>
            <li class="nav-item"><%= link_to "ログアウト", destroy_admin_session_path, class: "btn btn-outline-warning text-dark", method: :delete %></li>
            
            <!-- ログインしていない時 -->
            <% else %>
            <li class="nav-item"><%= link_to "商品一覧", items_path, class: "btn btn-outline-warning text-dark" %></li>
            <li class="nav-item"><%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-warning text-dark" %></li>
            <li class="nav-item"><%= link_to "About", about_path, class: "btn btn-outline-warning text-dark" %></li>
            <li class="nav-item"><%= link_to "ログイン", new_customer_session_path, class: "btn btn-outline-warning text-dark" %></li>
            <% end %>
            </ul>
            
            <div class="mt-3">
            <%= form_with url: search_path, method: :get, class: 'd-flex' do |f| %>
            <%= f.text_field :content, placeholder: "検索...", class: 'form-control' %>
            <%= f.submit '検索', class: 'ml-1 btn btn-outline-warning flex-shrink-0' %>
            <% end %>
            </div>
          </div>
        </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--FONTAWESOMEアイコンの読み込みの記述-->
    <script src="https://kit.fontawesome.com/61de06ea52.js" crossorigin="anonymous"></script>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>



 <body class="d-flex flex-column vh-100">
  <!--ヘッダー部分-->
  <div><%= render 'layouts/header' %></div>
  
  <!--ボディ部分-->
  <p class='text-success'><%= flash[:notice] %></p>
  <p class='text-danger'><%= flash[:alert] %></p>
  <%= yield %>
  
  <!--フッター部分-->
  <%= render "layouts/footer" %>
  
  </body>
</html>